name: 'hero-bot'
description: 'extract heros (contributor) from repo'
inputs:
  token:  
    description: 'Personal access tokens for access your repo'
    required: true
inputs:
  repos:  
    description: 'repos need to collection contributor'
    required: true
inputs:
  targetRepo:  
    description: 'repo to add collection contributor'
    required: true
    default: 'milvus-io/milvus'
inputs:
  orderKey:  
    description: 'contributor is ordered by this key'
    required: false
    default: 'login'
inputs:
  isAscend:  
    description: 'ascend or descend '
    required: false
    default: true
inputs:
  userTypeBlackList:  
    description: 'filter out user type'
    required: false
    default: 'Bot'
inputs:
  filePath:  
    description: 'path of file to add contributors'
    required: false
    default: 'README.md'
inputs:
  width:  
    description: 'width of contributor avator icon'
    required: false
    default: '40px'
inputs:
  showTotal:  
    description: 'show total number badge'
    required: false
    default: true

runs:
  using: 'node12'
  main: 'index.js'


