name: 'hero-bot-action'
description: 'extract heros (contributor) from repo'
inputs:
  token:  
    description: 'Personal access tokens for access your repo'
    required: true
  repos:  
    description: 'repos need to collection contributor'
    required: true
  targetRepo:  
    description: 'repo to add collection contributor'
    required: true
    default: 'milvus-io/milvus'
  orderKey:  
    description: 'contributor is ordered by this key'
    required: false
    default: 'login'
  isAscend:  
    description: 'ascend or descend '
    required: false
    default: true
  userTypeBlackList:  
    description: 'filter out user type'
    required: false
    default: 'Bot'
  filePath:  
    description: 'path of file to add contributors'
    required: false
    default: 'README.md'
  width:  
    description: 'width of contributor avator icon'
    required: false
    default: '40px'
  showTotal:  
    description: 'show total number badge'
    required: false
    default: true

runs:
  using: 'node12'
  main: 'index.js'


