name: 'hero-bot-action'
description: 'extract heros (contributor) from repos'
inputs:
  token:  
    description: 'Personal access tokens for access your repos'
    required: true
  repos:  
    description: 'repos need to collection contributors'
    required: true
  target:  
    description: 'target path to add collected contributors'
    required: true
    default: 'milvus-io/milvus/README.md'
  orderKey:  
    description: 'contributor is ordered by this key'
    required: false
    default: 'login'
  isAscend:  
    description: 'ascend or descend '
    required: false
    default: true
  userTypeBlackList:  
    description: 'filter out user type'
    required: false
    default: 'Bot'
  width:  
    description: 'width of contributor avator icon'
    required: false
    default: '40px'
  showTotal:  
    description: 'show total number badge'
    required: false
    default: true
  customUserConfig: 
    description: 'a json config file for adding custom user list'
    required: false
    default: null

runs:
  using: 'node14'
  main: 'dist/index.js'

