name: add contributor

on: push

jobs:
  contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: milvus-io/hero-bot@latest
        with:
          token: ${{ secrets.MYTOKEN }}
          repos: 'milvus-io/milvus,'
          target: 'milvus-io/hero-bot/README.md'
          isAscend: False
          width: '50px'
